apiVersion: v1
kind: Secret
metadata:
  name: ocir-secret
  namespace: node-app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ord.ocir.io": {
          "auth": "YXh0aWQ1M3BlZWRxL2x1aXMuZmxvcmV6QGJsYWNrcG9vbC5sYTp7cDBFb0pGQjR0blJnLmpbVzBZdA==",
          "email": "luis.florez@blackpool.la"
        }
      }
    }